name: firebase_tutorial
description: "A new Flutter project."

publish_to: "none"


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  cloud_firestore: ^5.6.8
  cupertino_icons: ^1.0.8
  
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  
  flex_color_picker: ^3.7.1
  flutter:
    sdk: flutter
  
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
 
