// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA28MUlQnV07R9mMznHn8O8RBQb-a2vOBc',
    appId: '1:538782597877:web:781e16f9d4b66e65a37bbc',
    messagingSenderId: '538782597877',
    projectId: 'fir-tutorial-4a144',
    authDomain: 'fir-tutorial-4a144.firebaseapp.com',
    storageBucket: 'fir-tutorial-4a144.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Yh63yrApsYl3aE7vXELx9CBwOWG0aWo',
    appId: '1:538782597877:android:6ecb180c21ad2d33a37bbc',
    messagingSenderId: '538782597877',
    projectId: 'fir-tutorial-4a144',
    storageBucket: 'fir-tutorial-4a144.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3qdt_uzal4pb34wxDp7tQabYyzXQmUvo',
    appId: '1:538782597877:ios:7aa766bc34be8537a37bbc',
    messagingSenderId: '538782597877',
    projectId: 'fir-tutorial-4a144',
    storageBucket: 'fir-tutorial-4a144.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3qdt_uzal4pb34wxDp7tQabYyzXQmUvo',
    appId: '1:538782597877:ios:7aa766bc34be8537a37bbc',
    messagingSenderId: '538782597877',
    projectId: 'fir-tutorial-4a144',
    storageBucket: 'fir-tutorial-4a144.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA28MUlQnV07R9mMznHn8O8RBQb-a2vOBc',
    appId: '1:538782597877:web:e11a08957305ac11a37bbc',
    messagingSenderId: '538782597877',
    projectId: 'fir-tutorial-4a144',
    authDomain: 'fir-tutorial-4a144.firebaseapp.com',
    storageBucket: 'fir-tutorial-4a144.firebasestorage.app',
  );
}
